### ISSUE TITLE
Add vs 2019 preview support

### ISSUE THREAD

**Issue by qdztxc** [zbrad/VsEmacs#17]
This great plugin doesn't support vs 2019 preview.
Is there a workaround to use it with vs 2019?

**Comment by qdztxc** [comment]
Any plan to support vs 2019?

**Comment by zbrad** [comment]
i'm trying out the rc now, so I'll see about updating this now.

**Comment by davidhite** [comment]
Thanks, will be appreciated!

**Comment by qdztxc** [comment]
Visual Studio 2019 is GA.
Hopes zbrad can spend some time to make it work. 
Thanks very much.

**Comment by davidhite** [comment]
I was able to get this built and working on the Visual Studio 2019 release.

Repair the VS2013 installation via Add/Remove programs (this restores the EnvDTE assembly that was removed by VS2017 or VS2019 installation)
Open the solution in VS2019
Change the targeted framework to 4.7.2
Add a reference to Microsoft.VisualStudio.Shell.Framework;
Add "using Microsoft.VisualStudio.Shell.Framework;" to CommandRouterProvider.cs (not sure if this is necessary)
Add a prerequisites section to source.extension.vsixmanifest
` <Prerequisites>`
`<Prerequisite Id="Microsoft.VisualStudio.Component.NuGet" Version="[16.0.28625.61,17.0)" DisplayName="NuGet package manager" />`
 `</Prerequisites>`

Change the install target to 16.0 in source.extension.vsixmanifest
Build the .vsix
Close visual studio
Run the .vsix
Open visual studio and select emacs from the keyboard options
 
This may need more work but should get you going for now.

**Comment by qdztxc** [comment]
> I was able to get this built and working on the Visual Studio 2019 release.
> 
> Repair the VS2013 installation via Add/Remove programs (this restores the EnvDTE assembly that was removed by VS2017 or VS2019 installation)
> Open the solution in VS2019
> Change the targeted framework to 4.7.2
> Add a reference to Microsoft.VisualStudio.Shell.Framework;
> Add "using Microsoft.VisualStudio.Shell.Framework;" to CommandRouterProvider.cs (not sure if this is necessary)
> Add a prerequisites section to source.extension.vsixmanifest
> ` <Prerequisites>`
> `<Prerequisite Id="Microsoft.VisualStudio.Component.NuGet" Version="[16.0.28625.61,17.0)" DisplayName="NuGet package manager" />`
> `</Prerequisites>`
> 
> Change the install target to 16.0 in source.extension.vsixmanifest
> Build the .vsix
> Close visual studio
> Run the .vsix
> Open visual studio and select emacs from the keyboard options
> 
> This may need more work but should get you going for now.

Could you please share your .vsix file?
I don't have VS2013 installation.
Thanks very much.

**Comment by davidhite** [comment]
Sure, It's not signed. You will need to extract the vsix from the attached zip.
[Microsoft.VisualStudio.Editor.EmacsEmulation.zip](https://github.com/zbrad/EmacsKeys/files/3055093/Microsoft.VisualStudio.Editor.EmacsEmulation.zip)

**Comment by billy-cole** [comment]
> 
> 
> Sure, It's not signed. You will need to extract the vsix from the attached zip.
> [Microsoft.VisualStudio.Editor.EmacsEmulation.zip](https://github.com/zbrad/EmacsKeys/files/3055093/Microsoft.VisualStudio.Editor.EmacsEmulation.zip)

Thank you so much! Been dying to try VS 2019, but really needed these bindings. Thanks again!

**Comment by qdztxc** [comment]
> Sure, It's not signed. You will need to extract the vsix from the attached zip.
> [Microsoft.VisualStudio.Editor.EmacsEmulation.zip](https://github.com/zbrad/EmacsKeys/files/3055093/Microsoft.VisualStudio.Editor.EmacsEmulation.zip)

Thank you sooooooo much! Finally I can use VS 2019. :)
