### ISSUE TITLE
Emacs Emulation does not work with Github Copilot

### ISSUE THREAD

**Issue by dtecta** [zbrad/VsEmacs#21]
I tried making Emacs Emulation work with Github Copilot. The problem is that Copilot expects Tab to accept a suggestion, however Tab does not interact with Copilot when Emacs Emulation is active. I've tried binding a new key to "Edit.InsertTab". However, this does not seem to have an effect. "Automatically indent when I type a tab" is disabled in C++ formatting. Is there a fix or workaround for this problem (other than disabling emacs emulation)?

**Comment by ganaware** [comment]
You can use right arrow key instead of tab:

go to Tools -> Options -> IntelliCode -> Completions for whole lines of code. Enable the setting named Apply completions for whole lines on right arrow.  Copilot is affected by this option.

https://learn.microsoft.com/en-us/visualstudio/intellicode/visual-studio-whole-line-completions

**Comment by dtecta** [comment]
> You can use right arrow key instead of tab:
> 
> go to Tools -> Options -> IntelliCode -> Completions for whole lines of code. Enable the setting named Apply completions for whole lines on right arrow. Copilot is affected by this option.
> 
> https://learn.microsoft.com/en-us/visualstudio/intellicode/visual-studio-whole-line-completions

Thanks, this is perfect!

**Comment by soh534** [comment]
> You can use right arrow key instead of tab:
> 
> go to Tools -> Options -> IntelliCode -> Completions for whole lines of code. Enable the setting named Apply completions for whole lines on right arrow. Copilot is affected by this option.
> 
> https://learn.microsoft.com/en-us/visualstudio/intellicode/visual-studio-whole-line-completions

This doesn't seem to be working for me
